process.env.TZ = 'America/New_York'

module.exports = {
  globals: {
    ALCHEMY_API_KEY: 'key_for_ALCHEMY_API_KEY',
    AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY: 'key_for_AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY',
    APPSFLYER_API_KEY: 'key_for_APPSFLYER_API_KEY',
    APPSFLYER_APP_ID: 123,
    DATADOG_CLIENT_TOKEN: 'key_for_DATADOG_CLIENT_TOKEN',
    DATADOG_PROJECT_ID: 123,
    INFURA_KEY: 'key_for_INFURA_KEY',
    ONESIGNAL_APP_ID: 123,
    OPENAI_API_KEY: 'key_for_OPENAI_API_KEY',
    QUICKNODE_ARBITRUM_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_BNB_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_MAINNET_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_SEPOLIA_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_ZORA_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_ZKSYNC_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_BLAST_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_AVAX_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_BASE_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_CELO_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_OP_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_POLYGON_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_WORLDCHAIN_RPC_URL: 'https://api.uniswap.org',
    QUICKNODE_ASTROCHAIN_SEPOLIA_RPC_URL: 'https://api.uniswap.org',
    SENTRY_DSN: 'http://sentry.com',
    SHAKE_CLIENT_ID: 123,
    SHAKE_CLIENT_SECRET: 123,
    SIMPLEHASH_API_KEY: 'key_for_SIMPLEHASH_API_KEY',
    SIMPLEHASH_API_URL: 'https://api.simplehash.com',
    STATSIG_PROXY_URL: 'https://api.statsig.com',
    TRADING_API_KEY: 'key_for_TRADING_API_KEY',
    UNISWAP_API_KEY: 'key_for_UNISWAP_API_KEY',
    WALLETCONNECT_PROJECT_ID: 123,
    FIREBASE_APP_CHECK_DEBUG_TOKEN: 'token',
  },
}
